"""Outillage d'analyse d'audience éditoriale.

`parsers` lit les exports (Search Console, CMS), `metrics` calcule les mesures
du diagnostic. L'interface Streamlit se trouve dans `app.py`, à la racine.
"""

from .parsers import (
    ExportGSC,
    charger_articles,
    charger_dossier_gsc,
    charger_gsc,
    charger_redirections,
    decoupe_url,
    section,
    to_number,
)
from .marfeel import (
    CANAUX,
    SITES,
    audience_fidele,
    charger_marfeel,
    compare_periodes,
    devine_origine,
    granularite_dominante,
    mix_canaux,
    series_hebdomadaires,
)
from .flux import Collecte, FLUX_PAR_DEFAUT, collecte, collecte_hors_ligne, lire_flux
from .palettes import (
    FAMILLES,
    MARQUEURS,
    Note,
    ProfilSucces,
    angles_a_retravailler,
    note_sujet,
    palette_chaude,
    palette_froide,
    profil_succes,
    sujets_orphelins,
)
from .suggestions import GABARITS, Gabarit, rendement_des_gabarits, suggere_titres
from .metrics import (
    RELANCES_MAX,
    SEUIL_CARTON,
    Relance,
    chaines_de_redirection,
    compare_sites,
    concentration,
    detecte_relances,
    evolution_annuelle,
    poids_des_sections,
    profil_cartons,
    reservoir,
    serie_mensuelle,
    stock_et_flux,
    sujets_communs,
    synthese_relances,
)

__all__ = [
    "CANAUX",
    "GABARITS",
    "Gabarit",
    "rendement_des_gabarits",
    "suggere_titres",
    "Collecte",
    "SITES",
    "audience_fidele",
    "charger_marfeel",
    "compare_periodes",
    "devine_origine",
    "granularite_dominante",
    "mix_canaux",
    "series_hebdomadaires",
    "ExportGSC",
    "FAMILLES",
    "FLUX_PAR_DEFAUT",
    "MARQUEURS",
    "Note",
    "ProfilSucces",
    "angles_a_retravailler",
    "collecte",
    "collecte_hors_ligne",
    "lire_flux",
    "note_sujet",
    "palette_chaude",
    "palette_froide",
    "profil_succes",
    "sujets_orphelins",
    "RELANCES_MAX",
    "Relance",
    "SEUIL_CARTON",
    "charger_articles",
    "charger_dossier_gsc",
    "chaines_de_redirection",
    "charger_gsc",
    "charger_redirections",
    "compare_sites",
    "concentration",
    "decoupe_url",
    "detecte_relances",
    "evolution_annuelle",
    "poids_des_sections",
    "profil_cartons",
    "reservoir",
    "section",
    "serie_mensuelle",
    "stock_et_flux",
    "sujets_communs",
    "synthese_relances",
    "to_number",
]
